// examples/events-lit/drum-machine/components.ts
import { LitElement, html, css, svg } from "lit";
import { customElement, property } from "lit/decorators.js";
import { on } from "../on-directive.ts";
import type { EventDescriptor } from "@remix-run/events";

@customElement("drum-layout")
export class Layout extends LitElement {
    static override styles = css`
        :host {
            box-sizing: border-box;
            display: flex;
            flex-direction: column;
            gap: 30px;
            width: 650px;
            margin: 0 auto;
            background: #2d2d2d;
            color: white;
            border-radius: 36px;
            padding: 30px 32px 36px;
        }
        * {
            box-sizing: border-box;
        }
        header {
            display: flex;
            justify-content: space-between;
            align-items: center;
            gap: 1rem;
        }
        .title {
            display: flex;
            align-items: end;
            line-height: 0.88;
            text-align: right;
            font-size: 1.5rem;
            font-weight: 700;
            position: relative;
            top: 1px;
        }
    `;

    override render() {
        return html`
            <header>
                <drum-logo></drum-logo>
                <div class="title">
                    LIT<br />
                    DRUM MACHINE
                </div>
            </header>
            <slot></slot>
        `;
    }
}

@customElement("equalizer-bar")
export class EqualizerBar extends LitElement {
    static override styles = css`
        :host {
            flex: 1;
            display: flex;
            flex-direction: column;
            gap: 4px;
        }
        .bar {
            flex: 1;
            width: 100%;
            border-radius: 4px;
        }
    `;

    @property({ type: Number })
    volume = 0;

    private colors = [
        "#FF3000",
        "#FF3000",
        "#E561C3",
        "#E561C3",
        "#FFD400",
        "#FFD400",
        "#64C146",
        "#64C146",
        "#1A72FF",
        "#1A72FF",
    ];

    override render() {
        const startIndexToShow = 10 - Math.round(this.volume * 10);

        return html`
            ${Array.from({ length: 10 }).map((_, index) => {
                return html`
                    <div
                        class="bar"
                        style="background: ${this.colors[index]}; opacity: ${index >=
                        startIndexToShow
                            ? 1
                            : 0.25}"
                    ></div>
                `;
            })}
        `;
    }
}

@customElement("control-group")
export class ControlGroup extends LitElement {
    static override styles = css`
        :host {
            display: grid;
            grid-template-columns: repeat(2, minmax(0, 1fr));
            grid-auto-rows: minmax(64px, auto);
            gap: 12px;
            align-items: stretch;
            justify-content: center;
            height: 200px;
        }
    `;

    override render() {
        return html`<slot></slot>`;
    }
}

@customElement("drum-button")
export class Button extends LitElement {
    static override styles = css`
        :host {
            display: block;
            height: 100%;
        }
        button {
            all: unset;
            letter-spacing: 1.25px;
            height: 100%;
            width: 100%;
            display: flex;
            align-items: flex-end;
            background: #666;
            border-radius: 12px;
            padding: 16px 20px;
            font-size: 0.75rem;
            font-weight: 700;
            box-sizing: border-box;
        }
        button:disabled {
            opacity: 0.25;
        }
        button:active:not(:disabled) {
            background: #555;
        }
    `;

    @property({ type: Boolean })
    disabled = false;

    @property({ attribute: false })
    events: EventDescriptor | EventDescriptor[] | null | undefined = null;

    override render() {
        return html`
            <button ${on(this.events)} ?disabled=${this.disabled}>
                <slot></slot>
            </button>
        `;
    }
}

@customElement("triangle-icon")
export class Triangle extends LitElement {
    static override styles = css`
        svg {
            width: 18px;
            height: 18px;
        }
    `;

    @property({ type: String })
    orientation: "up" | "down" = "up";

    @property({ type: String })
    label = "";

    override render() {
        const up = "5,1.34 9.33,8.66 0.67,8.66";
        const down = "5,8.66 9.33,1.34 0.67,1.34";
        const points = this.orientation === "up" ? up : down;

        return svg`
      <svg aria-label=${this.label} viewBox="0 0 10 10">
        <polygon points=${points} fill="currentColor" />
      </svg>
    `;
    }
}

@customElement("tempo-button")
export class TempoButton extends LitElement {
    static override styles = css`
        :host {
            display: block;
            --tempo-button-border-radius: 0;
        }
        button {
            all: unset;
            flex: 1;
            width: 100%;
            min-height: 0;
            height: 100%;
            background: #666;
            display: flex;
            align-items: center;
            justify-content: center;
            box-sizing: border-box;
            border-radius: var(--tempo-button-border-radius);
            padding: 10px 0;
            overflow: hidden;
        }
        button:active {
            background: #555;
        }
    `;

    @property({ type: String })
    orientation: "up" | "down" = "up";

    @property({ attribute: false })
    events: EventDescriptor | EventDescriptor[] | null | undefined = null;

    override render() {
        return html`
            <button ${on(this.events)}>
                <triangle-icon
                    orientation=${this.orientation}
                    label=${this.orientation}
                ></triangle-icon>
            </button>
        `;
    }
}

declare global {
    interface HTMLElementTagNameMap {
        "drum-layout": Layout;
        "equalizer-bar": EqualizerBar;
        "control-group": ControlGroup;
        "drum-button": Button;
        "triangle-icon": Triangle;
        "tempo-button": TempoButton;
    }
}

// examples/dom-signals/drum-machine/components.tsx
import type { Remix } from "@remix-run/dom";
import { Logo } from "./logo";

export function Layout({ children }: { children: Remix.RemixNode }) {
    return (
        <div
            css={{
                boxSizing: "border-box",
                "& *": {
                    boxSizing: "border-box",
                },
                display: "flex",
                flexDirection: "column",
                gap: "30px",
                width: "min(420px, calc(100vw - 40px))",
                margin: "0 auto",
                background: "#2D2D2D",
                color: "white",
                borderRadius: "36px",
                padding: "30px 32px 36px 32px",
            }}
        >
            <header
                css={{
                    display: "flex",
                    justifyContent: "space-between",
                    alignItems: "center",
                    gap: "1rem",
                }}
            >
                <Logo />
                <div
                    css={{
                        display: "flex",
                        alignItems: "end",
                        lineHeight: "0.88",
                        textAlign: "right",
                        fontSize: "1.5rem",
                        fontWeight: 700,
                        position: "relative",
                        top: "1px",
                    }}
                >
                    REMIX 3<br />
                    DRUM MACHINE
                </div>
            </header>

            {children}
        </div>
    );
}

export function EqualizerBar(this: Remix.Handle) {
    let colors = [
        "#FF3000",
        "#FF3000",
        "#E561C3",
        "#E561C3",
        "#FFD400",
        "#FFD400",
        "#64C146",
        "#64C146",
        "#1A72FF",
        "#1A72FF",
    ];

    return ({ volume }: { volume: number /* 0-1 */ }) => {
        let startIndexToShow = 10 - Math.round(volume * 10);
        return (
            <div
                css={{
                    flex: 1,
                    display: "flex",
                    flexDirection: "column",
                    gap: "4px",
                }}
            >
                {Array.from({ length: 10 }).map((_, index) => (
                    <div
                        css={{
                            flex: 1,
                            width: "100%",
                            borderRadius: "4px",
                            background: colors[index],
                            opacity: index >= startIndexToShow ? 1 : 0.25,
                        }}
                    />
                ))}
            </div>
        );
    };
}

export function ControlGroup({ children, css, ...rest }: Remix.Props<"div">) {
    return (
        <div
            {...rest}
            css={{
                display: "grid",
                gridTemplateColumns: "repeat(2, minmax(0, 1fr))",
                gridAutoRows: "minmax(64px, auto)",
                gap: "12px",
                alignItems: "stretch",
                justifyContent: "center",
                ...css,
            }}
        >
            {children}
        </div>
    );
}

export function Button({ children, ...rest }: Remix.Props<"button">) {
    return (
        <button
            {...rest}
            css={{
                all: "unset",
                letterSpacing: 1.25,
                height: "100%",
                display: "flex",
                alignItems: "flex-end",
                background: "#666",
                borderRadius: "12px",
                padding: "16px 20px",
                fontSize: "0.75rem",
                fontWeight: 700,
                boxSizing: "border-box",
                "&:disabled": {
                    opacity: 0.25,
                },
                "&:active": {
                    background: "#555",
                },
            }}
        >
            {children}
        </button>
    );
}

export type DecayGenerator = Generator<number, number, number>;

export function createExponentialDecayGenerator(
    halfLifeMs: number,
    startValue: number,
    startMs: number,
): DecayGenerator {
    const localEpsilon = 0.001;
    function* decay(): Generator<number, number, number> {
        let value = startValue;
        let lastMs = startMs;
        while (value > localEpsilon) {
            const input = yield value;
            const nowMs = typeof input === "number" ? input : performance.now();
            const deltaMs = Math.max(0, nowMs - lastMs);
            lastMs = nowMs;
            const decayFactor = Math.pow(0.5, deltaMs / halfLifeMs);
            value = value * decayFactor;
        }
        return 0;
    }
    return decay();
}

export function createEnvelopeLoop(render: () => void, epsilon: number = 0.001) {
    let frameId: number | null = null;

    type EnvelopeState = {
        value: number;
        halfLifeMs: number;
        gen: DecayGenerator | null;
    };

    let envelopes: EnvelopeState[] = [];

    function ensureLoop() {
        if (frameId == null) frameId = requestAnimationFrame(tick);
    }

    function tick(now: number) {
        let anyActive = false;
        for (let i = 0; i < envelopes.length; i++) {
            const state = envelopes[i];
            if (state?.gen) {
                const result = state.gen.next(now);
                state.value = result.value ?? 0;
                if (result.done) {
                    state.gen = null;
                    state.value = 0;
                } else if (state.value > epsilon) {
                    anyActive = true;
                }
            }
        }
        if (anyActive) {
            render();
            frameId = requestAnimationFrame(tick);
        } else {
            frameId = null;
        }
    }

    function createEnvelope(halfLifeMs: number) {
        const state: EnvelopeState = { value: 0, halfLifeMs, gen: null };
        envelopes.push(state);
        return {
            get value() {
                return state.value;
            },
            trigger(amplitude: number = 1) {
                const now = performance.now();
                state.value = amplitude;
                state.gen = createExponentialDecayGenerator(state.halfLifeMs, amplitude, now);
                void state.gen.next();
                ensureLoop();
            },
        };
    }

    return { createEnvelope };
}

export function Triangle({ label, orientation }: { label: string; orientation: "up" | "down" }) {
    let up = "5,1.34 9.33,8.66 0.67,8.66";
    let down = "5,8.66 9.33,1.34 0.67,1.34";
    return (
        <svg
            aria-label={label}
            viewBox="0 0 10 10"
            css={{
                width: 18,
                height: 18,
            }}
        >
            <polygon points={orientation === "up" ? up : down} fill="currentColor" />
        </svg>
    );
}

interface TempoButtonProps extends Remix.Props<"button"> {
    orientation: "up" | "down";
}

export function TempoButton({ orientation, css, ...rest }: TempoButtonProps) {
    return (
        <button
            {...rest}
            css={{
                all: "unset",
                flex: 1,
                width: "100%",
                minHeight: 0,
                background: "#666",
                display: "flex",
                alignItems: "center",
                justifyContent: "center",
                borderRadius: "0",
                padding: "10px 0",
                "&:active": {
                    background: "#555",
                },
                ...css,
            }}
        >
            <Triangle label={orientation} orientation={orientation} />
        </button>
    );
}
