// examples/dom-signals/drum-machine/app.tsx
import { connect, type Remix } from "@remix-run/dom";
import { events } from "@remix-run/events";
import { Drummer } from "./signal-drummer.ts";
import { tempoTap } from "../../shared/tempo-event.ts";
import { arrowDown, arrowUp, space } from "@remix-run/events/key";
import { press } from "@remix-run/events/press";
import {
    Button,
    ControlGroup,
    createEnvelopeLoop,
    EqualizerBar,
    Layout,
    TempoButton,
} from "./components.tsx";
import { component } from "../signal-component.tsx";

export function DrumMachine(this: Remix.Handle<Drummer>) {
    let drummer = new Drummer(80);

    events(document, [
        space(() => {
            drummer.toggle();
        }),
        arrowUp(() => {
            drummer.setTempo(drummer.bpm + 1);
        }),
        arrowDown(() => {
            drummer.setTempo(drummer.bpm - 1);
        }),
    ]);

    this.context.set(drummer);

    return () => (
        <Layout>
            <Equalizer />
            <DrumControls />
        </Layout>
    );
}

function Equalizer(this: Remix.Handle) {
    let drummer = this.context.get(DrumMachine);

    let kickVolumes = [0.4, 0.8, 0.3, 0.1];
    let snareVolumes = [0.4, 1, 0.7];
    let hatVolumes = [0.1, 0.8];

    let { createEnvelope } = createEnvelopeLoop(() => this.update());

    let kickEnv = createEnvelope(220);
    let snareEnv = createEnvelope(280);
    let hatEnv = createEnvelope(120);

    events(drummer, [
        Drummer.kick(() => {
            kickEnv.trigger(1);
        }),
        Drummer.snare(() => {
            snareEnv.trigger(1);
        }),
        Drummer.hat(() => {
            hatEnv.trigger(1);
        }),
    ]);

    return () => {
        let kicks = kickVolumes.map(volume => kickEnv.value * volume);
        let snares = snareVolumes.map(volume => snareEnv.value * volume);
        let hats = hatVolumes.map(volume => hatEnv.value * volume);

        return (
            <div
                css={{
                    display: "flex",
                    background: "black",
                    borderRadius: "12px",
                    padding: "12px",
                    width: "100%",
                    height: "300px",
                    gap: "4px",
                }}
            >
                {/* kick */}
                <EqualizerBar volume={kicks[0] ?? 0} />
                <EqualizerBar volume={kicks[1] ?? 0} />
                <EqualizerBar volume={kicks[2] ?? 0} />
                <EqualizerBar volume={kicks[3] ?? 0} />

                {/* snare */}
                <EqualizerBar volume={snares[0] ?? 0} />
                <EqualizerBar volume={snares[1] ?? 0} />
                <EqualizerBar volume={snares[2] ?? 0} />

                {/* hat */}
                <EqualizerBar volume={hats[0] ?? 0} />
                <EqualizerBar volume={hats[1] ?? 0} />
            </div>
        );
    };
}

const DrumControls = component(function (this: Remix.Handle) {
    let drummer = this.context.get(DrumMachine);
    let stop: HTMLButtonElement;
    let play: HTMLButtonElement;

    return () => {
        let isPlaying = drummer.isPlaying;

        return (
            <ControlGroup
                css={{
                    "& button:focus-visible": {
                        outline: "2px solid #2684FF",
                        outlineOffset: "2px",
                    },
                }}
            >
                <Button
                    on={[
                        tempoTap(event => {
                            drummer.play(event.detail);
                        }),
                    ]}
                >
                    SET TEMPO
                </Button>
                <TempoDisplay />
                <Button
                    disabled={isPlaying}
                    on={[
                        connect(event => (play = event.currentTarget)),
                        press(() => {
                            drummer.play();
                            this.queueTask(() => {
                                stop.focus();
                            });
                        }),
                    ]}
                >
                    PLAY
                </Button>
                <Button
                    disabled={!isPlaying}
                    on={[
                        connect(event => (stop = event.currentTarget)),
                        press(() => {
                            drummer.stop();
                            this.queueTask(() => {
                                play.focus();
                            });
                        }),
                    ]}
                >
                    STOP
                </Button>
            </ControlGroup>
        );
    };
});

const TempoDisplay = component(function (this: Remix.Handle) {
    let drummer = this.context.get(DrumMachine);
    return () => {
        let bpm = drummer.bpm;

        return (
            <div
                css={{
                    display: "flex",
                    gap: "10px",
                    alignItems: "stretch",
                }}
            >
                <div
                    css={{
                        display: "flex",
                        flex: 1,
                        background: "#0B1B05",
                        color: "#64C146",
                        padding: "18px",
                        borderTopLeftRadius: "12px",
                        borderBottomLeftRadius: "12px",
                        alignItems: "flex-end",
                        justifyContent: "space-between",
                        boxSizing: "border-box",
                    }}
                >
                    <div
                        css={{
                            fontSize: "0.8rem",
                            fontWeight: 700,
                            letterSpacing: "0.08em",
                        }}
                    >
                        BPM
                    </div>
                    <div
                        css={{
                            flex: 1,
                            fontSize: "2.6rem",
                            fontWeight: 700,
                            textAlign: "right",
                            fontFamily: "JetBrains Mono, monospace",
                            lineHeight: 1,
                        }}
                    >
                        {bpm}
                    </div>
                </div>
                <div
                    css={{
                        width: "56px",
                        display: "grid",
                        gridTemplateRows: "1fr 1fr",
                        gap: "10px",
                    }}
                >
                    <TempoButton
                        css={{ borderTopRightRadius: "12px", borderBottomRightRadius: "0" }}
                        orientation="up"
                        on={press(() => {
                            drummer.setTempo(bpm + 1);
                        })}
                    />
                    <TempoButton
                        css={{ borderTopRightRadius: "0", borderBottomRightRadius: "12px" }}
                        orientation="down"
                        on={press(() => {
                            drummer.setTempo(bpm - 1);
                        })}
                    />
                </div>
            </div>
        );
    };
});

// examples/events-lit/drum-machine/app.ts
import { LitElement, html, css } from "lit";
import { customElement, state } from "lit/decorators.js";
import { createContext, ContextProvider, ContextConsumer } from "@lit/context";
import { events } from "@remix-run/events";
import { arrowDown, arrowUp, space } from "@remix-run/events/key";
import { press } from "@remix-run/events/press";
import { Drummer } from "../../shared/event-drummer.ts";
import { tempoTap } from "../../shared/tempo-event.ts";
import "./components.ts";
import "./logo.ts";

// Create context for the Drummer instance
export const drummerContext = createContext<Drummer>("drummer");

@customElement("drum-machine")
export class DrumMachine extends LitElement {
    static override styles = css`
        :host {
            display: block;
        }
    `;

    drummer = new Drummer(80);
    private provider = new ContextProvider(this, {
        context: drummerContext,
        initialValue: this.drummer,
    });

    private cleanupKeyboard?: () => void | (() => void)[];

    override connectedCallback() {
        super.connectedCallback();

        // Set up keyboard event listeners
        this.cleanupKeyboard = events(document, [
            space(() => {
                this.drummer.toggle();
            }),
            arrowUp(() => {
                this.drummer.setTempo(this.drummer.bpm + 1);
            }),
            arrowDown(() => {
                this.drummer.setTempo(this.drummer.bpm - 1);
            }),
        ]);
    }

    override disconnectedCallback() {
        super.disconnectedCallback();
        if (this.cleanupKeyboard) {
            if (Array.isArray(this.cleanupKeyboard)) {
                this.cleanupKeyboard.forEach(fn => fn());
            } else {
                this.cleanupKeyboard();
            }
        }
    }

    override render() {
        return html`
            <drum-layout>
                <drum-equalizer></drum-equalizer>
                <drum-controls></drum-controls>
            </drum-layout>
        `;
    }
}

@customElement("drum-equalizer")
export class Equalizer extends LitElement {
    static override styles = css`
        :host {
            display: block;
        }
        .container {
            display: flex;
            background: black;
            border-radius: 12px;
            padding: 12px;
            height: 300px;
            gap: 4px;
            box-sizing: border-box;
        }
    `;

    drummer!: Drummer;
    private _consumer = new ContextConsumer(this, {
        context: drummerContext,
        subscribe: true,
        callback: value => {
            this.drummer = value;
            this.requestUpdate();
        },
    });

    private kickVolumes = [0.4, 0.8, 0.3, 0.1];
    private snareVolumes = [0.4, 1, 0.7];
    private hatVolumes = [0.1, 0.8];

    private frameId: number | null = null;
    private kickEnv?: { value: number; trigger: (amplitude?: number) => void };
    private snareEnv?: { value: number; trigger: (amplitude?: number) => void };
    private hatEnv?: { value: number; trigger: (amplitude?: number) => void };

    private cleanupDrummer?: () => void | (() => void)[];

    override connectedCallback() {
        super.connectedCallback();

        // Create envelopes
        this.kickEnv = this.createEnvelope(220);
        this.snareEnv = this.createEnvelope(280);
        this.hatEnv = this.createEnvelope(120);

        // Set up drum event listeners
        this.cleanupDrummer = events(this.drummer, [
            Drummer.kick(() => {
                this.kickEnv?.trigger(1);
            }),
            Drummer.snare(() => {
                this.snareEnv?.trigger(1);
            }),
            Drummer.hat(() => {
                this.hatEnv?.trigger(1);
            }),
        ]);
    }

    override disconnectedCallback() {
        super.disconnectedCallback();
        if (this.cleanupDrummer) {
            if (Array.isArray(this.cleanupDrummer)) {
                this.cleanupDrummer.forEach(fn => fn());
            } else {
                this.cleanupDrummer();
            }
        }
        if (this.frameId != null) {
            cancelAnimationFrame(this.frameId);
        }
    }

    private createExponentialDecayGenerator(
        halfLifeMs: number,
        startValue: number,
        startMs: number,
    ): Generator<number, number, number> {
        const localEpsilon = 0.001;
        function* decay(): Generator<number, number, number> {
            let value = startValue;
            let lastMs = startMs;
            while (value > localEpsilon) {
                const input = yield value;
                const nowMs = typeof input === "number" ? input : performance.now();
                const deltaMs = Math.max(0, nowMs - lastMs);
                lastMs = nowMs;
                const decayFactor = Math.pow(0.5, deltaMs / halfLifeMs);
                value = value * decayFactor;
            }
            return 0;
        }
        return decay();
    }

    private ensureLoop() {
        if (this.frameId == null) {
            this.frameId = requestAnimationFrame(now => this.tick(now));
        }
    }

    private envelopeStates: Array<{
        value: number;
        halfLifeMs: number;
        gen: Generator<number, number, number> | null;
    }> = [];

    private tick(now: number) {
        let anyActive = false;
        const epsilon = 0.001;

        for (let i = 0; i < this.envelopeStates.length; i++) {
            const state = this.envelopeStates[i];
            if (state && state.gen) {
                const result = state.gen.next(now);
                state.value = result.value ?? 0;
                if (result.done) {
                    state.gen = null;
                    state.value = 0;
                } else if (state.value > epsilon) {
                    anyActive = true;
                }
            }
        }

        if (anyActive) {
            this.requestUpdate();
            this.frameId = requestAnimationFrame(now => this.tick(now));
        } else {
            this.frameId = null;
        }
    }

    private createEnvelope(halfLifeMs: number) {
        const state: {
            value: number;
            halfLifeMs: number;
            gen: Generator<number, number, number> | null;
        } = { value: 0, halfLifeMs, gen: null };

        this.envelopeStates.push(state);

        return {
            get value() {
                return state.value;
            },
            trigger: (amplitude: number = 1) => {
                const now = performance.now();
                state.value = amplitude;
                state.gen = this.createExponentialDecayGenerator(halfLifeMs, amplitude, now);
                state.gen.next();
                this.ensureLoop();
            },
        };
    }

    override render() {
        const kicks = this.kickEnv
            ? this.kickVolumes.map(volume => this.kickEnv!.value * volume)
            : [0, 0, 0, 0];
        const snares = this.snareEnv
            ? this.snareVolumes.map(volume => this.snareEnv!.value * volume)
            : [0, 0, 0];
        const hats = this.hatEnv
            ? this.hatVolumes.map(volume => this.hatEnv!.value * volume)
            : [0, 0];

        return html`
            <div class="container">
                ${kicks.map(volume => html`<equalizer-bar .volume=${volume}></equalizer-bar>`)}
                ${snares.map(volume => html`<equalizer-bar .volume=${volume}></equalizer-bar>`)}
                ${hats.map(volume => html`<equalizer-bar .volume=${volume}></equalizer-bar>`)}
            </div>
        `;
    }
}

@customElement("drum-controls")
export class DrumControls extends LitElement {
    static override styles = css`
        :host {
            display: block;
        }
        button:focus-visible {
            outline: 2px solid #2684ff;
            outline-offset: 2px;
        }
    `;

    drummer!: Drummer;
    private _consumer = new ContextConsumer(this, {
        context: drummerContext,
        subscribe: true,
        callback: value => {
            this.drummer = value;
            this.requestUpdate();
        },
    });

    @state()
    private isPlaying = false;

    private playButton?: HTMLButtonElement;
    private stopButton?: HTMLButtonElement;
    private cleanupDrummer?: () => void | (() => void)[];

    override connectedCallback() {
        super.connectedCallback();
        this.cleanupDrummer = events(this.drummer, [
            Drummer.change(() => {
                this.isPlaying = this.drummer.isPlaying;
                this.requestUpdate();
            }),
        ]);
    }

    override disconnectedCallback() {
        super.disconnectedCallback();
        if (this.cleanupDrummer) {
            if (Array.isArray(this.cleanupDrummer)) {
                this.cleanupDrummer.forEach(fn => fn());
            } else {
                this.cleanupDrummer();
            }
        }
    }

    override render() {
        return html`
            <control-group>
                <drum-button
                    .events=${tempoTap(event => {
                        this.drummer.play(event.detail);
                    })}
                >
                    SET TEMPO
                </drum-button>
                <tempo-display></tempo-display>
                <drum-button
                    .disabled=${this.isPlaying}
                    .events=${press(() => {
                        this.drummer.play();
                        setTimeout(() => {
                            this.stopButton?.focus();
                        });
                    })}
                >
                    PLAY
                </drum-button>
                <drum-button
                    .disabled=${!this.isPlaying}
                    .events=${press(() => {
                        this.drummer.stop();
                        setTimeout(() => {
                            this.playButton?.focus();
                        });
                    })}
                >
                    STOP
                </drum-button>
            </control-group>
        `;
    }
}

@customElement("tempo-display")
export class TempoDisplay extends LitElement {
    static override styles = css`
        :host {
            display: block;
            height: 100%;
        }
        .container {
            display: flex;
            gap: 10px;
            align-items: stretch;
            height: 100%;
        }
        .bpm-display {
            height: 100%;
            display: flex;
            flex: 1;
            background: #0b1b05;
            color: #64c146;
            padding: 18px;
            border-top-left-radius: 12px;
            border-bottom-left-radius: 12px;
            align-items: flex-end;
            justify-content: space-between;
            box-sizing: border-box;
        }
        .bpm-label {
            font-size: 0.8rem;
            font-weight: 700;
            letter-spacing: 0.08em;
        }
        .bpm-value {
            flex: 1;
            font-size: 2.6rem;
            font-weight: 700;
            text-align: right;
            font-family: "JetBrains Mono", monospace;
            line-height: 1;
        }
        .buttons {
            width: 56px;
            display: grid;
            grid-template-rows: 1fr 1fr;
            gap: 10px;
        }
        tempo-button {
            flex: 1;
        }
    `;

    drummer!: Drummer;
    private _consumer = new ContextConsumer(this, {
        context: drummerContext,
        subscribe: true,
        callback: value => {
            this.drummer = value;
            this.requestUpdate();
        },
    });

    @state()
    private bpm = 90;

    private cleanupDrummer?: () => void | (() => void)[];

    override connectedCallback() {
        super.connectedCallback();
        this.bpm = this.drummer.bpm;
        this.cleanupDrummer = events(this.drummer, [
            Drummer.change(() => {
                this.bpm = this.drummer.bpm;
                this.requestUpdate();
            }),
        ]);
    }

    override disconnectedCallback() {
        super.disconnectedCallback();
        if (this.cleanupDrummer) {
            if (Array.isArray(this.cleanupDrummer)) {
                this.cleanupDrummer.forEach(fn => fn());
            } else {
                this.cleanupDrummer();
            }
        }
    }

    override render() {
        return html`
            <div class="container">
                <div class="bpm-display">
                    <div class="bpm-label">BPM</div>
                    <div class="bpm-value">${this.bpm}</div>
                </div>
                <div class="buttons">
                    <tempo-button
                        style="--tempo-button-border-radius: 0 12px 0 0;"
                        orientation="up"
                        .events=${press(() => {
                            this.drummer.setTempo(this.bpm + 1);
                        })}
                    ></tempo-button>
                    <tempo-button
                        style="--tempo-button-border-radius: 0 0 12px 0;"
                        orientation="down"
                        .events=${press(() => {
                            this.drummer.setTempo(this.bpm - 1);
                        })}
                    ></tempo-button>
                </div>
            </div>
        `;
    }
}

declare global {
    interface HTMLElementTagNameMap {
        "drum-machine": DrumMachine;
        "drum-equalizer": Equalizer;
        "drum-controls": DrumControls;
        "tempo-display": TempoDisplay;
    }
}
